---

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Reset hosts file
  copy:
    src: files/etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"

- name: Truncate audit logs
  file:
    state: "{{ item.state }}"
    path: "{{ item.path }}"
    owner: root
    group: utmp
    mode: "{{ item.mode }}"
  loop:
  - { path: /var/log/wtmp,    state: absent, mode: "0664" }
  - { path: /var/log/lastlog, state: absent, mode: "{{ last_log_mode }}" }
  - { path: /var/log/wtmp,    state: touch,  mode: "0664" }
  - { path: /var/log/lastlog, state: touch,  mode: "{{ last_log_mode }}" }

- name: Remove cloud-init lib dir and logs
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - /var/lib/cloud
  - /var/log/cloud-init.log
  - /var/log/cloud-init-output.log
  - /var/run/cloud-init

- name: Find temp files
  find:
    depth: 1
    file_type: any
    paths:
    - /tmp
    - /var/tmp
    pattern: '*'
  register: temp_files

- name: Reset temp space
  file:
    state: absent
    path: "{{ item.path }}"
  loop: "{{ temp_files.files }}"

- name: Find SSH host keys
  find:
    path: /etc/ssh
    pattern: 'ssh_host_*'
  register: ssh_host_keys

- name: Remove SSH host keys
  file:
    state: absent
    path: "{{ item.path }}"
  loop: "{{ ssh_host_keys.files }}"

- name: Remove SSH authorized users
  file:
    state: absent
    path: "{{ item.path }}"
  loop:
  - { path: /root/.ssh/authorized_keys }
  - { path: "/home/{{ ansible_env.SUDO_USER }}/.ssh/authorized_keys" }

- name: Truncate all remaining log files in /var/log
  shell:
    cmd: |
      find /var/log -type f -iname '*.log' | xargs truncate -s 0
- name: Delete all logrotated log zips
  shell:
    cmd: |
      find /var/log -type f -name '*.gz' -exec rm {} +
- name: Remove swapfile
  file:
    state: "{{ item.state }}"
    path: "{{ item.path }}"
  loop:
  - { path: /swapfile, state: absent }
  - { path: /mnt/resource/swapfile, state: absent }
  when: ansible_memory_mb.swap.total != 0

- name: Truncate shell history
  file:
    state: absent
    path: "{{ item.path }}"
  loop:
  - { path: /root/.bash_history }
  - { path: "/home/{{ ansible_env.SUDO_USER }}/.bash_history" }
