---

- name: Define file modes
  set_fact:
    last_log_mode:   "0644"
    machine_id_mode: "0444"


- name: Disable swap service and ensure it is masked
  systemd:
    name: temp-disk-swapfile
    enabled: no
    masked: yes
  when: ansible_memory_mb.swap.total != 0

- name: Remove RHEL subscription
  block:
    - name: Remove subscriptions
      rhsm_repository:
        name: '*'
        state: absent
    - name: Unregister system
      redhat_subscription:
        state: absent
    - name: clean local subscription data
      command: subscription-manager clean
  when: ansible_distribution == "RedHat"
  ignore_errors: true

- name: Remove yum package caches
  yum:
    autoremove: yes
    lock_timeout: 60

- name: Remove yum package lists
  command: /usr/bin/yum -y clean all

- name: Reset network interface IDs
  shell: sed -i '/^\(HWADDR\|UUID\)=/d' /etc/sysconfig/network-scripts/ifcfg-*

- name: Remove the kickstart log
  file:
    state: absent
    path: /root/anaconda-ks.cfg
