---

- name: be sure to include the proper {{ hardening | lower }} variables based on os family
  include_vars: "{{ hardening | lower }}-{{ ansible_facts['os_family'] | lower }}.yml"
  when:
    - hardening | lower != "none"
    - hardening | lower != ""

- name: be sure to include the proper {{ hardening | lower }} tasks based on os family
  include: "{{ hardening | lower }}-{{ ansible_facts['os_family'] | lower }}.yml"
  when:
    - hardening | lower != "none"
    - hardening | lower != ""
